### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by CCorfield** [SeanNaren/CTCNetworkClient#10]
I noticed an opportunity to do a bit of divide and conquer -- you can generate a table of labels for both the training and testing transcripts by consolidating duplicated code into a routine, such as the following:

local function convertLineToLabels(labels, line)
    local label = {}
    line = string.lower(line)
    -- Remove: beginning space, BOS, EOS, fileid, final space
    line = line:gsub('^%s_',''):gsub('<s>',''):gsub('</s>',''):gsub('%(.+%)',''):gsub('%s_$','')
    --Remove the space at the end of the line.
    for i = 1, #line do
        local character = string:sub(i, i)
        table.insert(label, alphabetMapping[character])
    end
    table.insert(labels, label)
end

I have chained together regular expressions to delete everything but the desired text, for both the AN4 training and testing transcripts. I have no idea why Lua has implemented its own syntax for RE's, when there are perfectly good precedents, someone above my pay grade will have to answer that one.

My sense is that for both the training and testing data sets you can fill in the same data structure with  triplets of {audio, truth text, labels}; this would make AudioData.lua more compact, and also be a useful template for other projects, such as VoxForge or TEDlium. Also, you can move the various parameters such as windowsize, stride, set sizes, and file locations into AudioData.lua. Fwiw, it is in practice a class, tied to the AN4 corpus, which supplies a table of the form {audio, truth text, labels} to the training, testing, and batch modules. Then, when you deal with other speech corpora, you can write a class which prepares their data, and offers them up in the same format. To extend the horizons a little bit: if you use CMU's lexicon, you can try out training your nets to generate  phonemes and look at the phoneme error rate, which is arguably a better measure of how well the net is doing, and there are some 'tricks of the trade' you can leverage to turn them into correctly spelled word sequences, but that will have to be the topic of another conversation. Cheers from bat cave, CC

**Comment by SeanNaren** [comment]
Again thanks for your help! I've incorporated your new method into AN4 with some tweaks to get rid of string identifiers. Also combined transcripts and the dataset together :)

I'm not sure about merging the parameters as well into the AudioData class because I thought it would be suitable to leave them in one place to be changed, would you agree?

I've also merged a branch into master that offloads some of the modules into a separate repo which can be installed via:

`luarocks install https://raw.githubusercontent.com/SeanNaren/CTCHelpers/master/ctchelpers-scm-1.rockspec`
