### ISSUE TITLE
Realtime microphone prediction

### ISSUE THREAD

**Issue by lauleehong** [SeanNaren/CTCNetworkClient#90]
Hi,

I'm able to get acceptable results from short (and loud) recorded sentences, using the pre-trained DeepSpeech model trained from LibreSpeech.

Any idea how I can implement prediction.lua based on realtime speech detection using my microphone?

**Comment by SeanNaren** [comment]
This would be a bit difficult since the base code is in lua, but a http api that exposes the model via making JSON API calls would be a good way to interface with a microphone where the code is written in python for example. A good place to start for the http api would be the waffle library [here](https://github.com/benglard/waffle)!
